---
title: "Untitled"
author: "Xiangxiong Feng"
date: "2023-11-30"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(modelr)
library(p8105.datasets)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

theme_set(theme_minimal() + theme(legend.position = "bottom"))


```

# Problem 2 

## Download dataset

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

## Bootstrap and linear model

```{r}
weather_bootstrap =
  weather_df|>
  modelr::bootstrap(n = 5000)|>
  mutate(
    models = map(strap, \(df) lm(tmax ~ tmin + prcp, data = df)),
    tidy_results = map(models, broom::tidy),
    glance_results = map(models, broom::glance))|>
  select(tidy_results, glance_results, .id)|>
  unnest(tidy_results, glance_results)|>
  select(.id, term, estimate, r.squared)|>
  group_by(.id)|>
  summarize(log_beta12 = log(estimate[2]) + log(estimate[3]),
            r_squared = r.squared)|>
  distinct()

```


## Distribution of log(beta_1 * beta_2)

```{r}
weather_bootstrap|>
  ggplot(aes(x=log_beta12))+
  geom_density() + ggtitle('distribution of log(beta_1 * beta_2)')
```



The distribution is skewed to the left. The density is highest when values are around 
-5 to -6.



## Distribution of r_squared





